#!/bin/sh

set -eu

# shellcheck source=../../../scripts/bin/pwnlib
. /usr/bin/pwnlib

# Wait for Bettercap
until nc -zv 127.0.0.1 8081 >/dev/null 2>&1; do sleep 1; done

# Wait for PwnGRID
until nc -zv 127.0.0.1 8666 >/dev/null 2>&1; do sleep 1; done

# Fixes:
# https://github.com/piwheels/packages/issues/59
if [ -e /usr/lib/arm-linux-gnueabihf/libatomic.so.1 ]; then
	export LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1
fi

# Create empty image file if it does not exist
# (prevents flask exception on first run)
if [ ! -f /root/pwnagotchi.png ]; then
	touch /root/pwnagotchi.png
fi

exec 2>&1
if is_auto_mode; then
	exec pwnagotchi
else
	exec pwnagotchi --manual
fi
