#!/bin/sh

set -eu

# shellcheck source=../../../scripts/bin/pwnlib
. /usr/bin/pwnlib

# Start monitor interface
start_monitor_interface

exec 2>&1
if is_auto_mode_no_delete; then
	exec bettercap -no-colors -caplet pwnagotchi-auto -iface "${PWNAGOTCHI_IFACE_MON:?}"
else
	exec bettercap -no-colors -caplet pwnagotchi-manual -iface "${PWNAGOTCHI_IFACE_MON:?}"
fi
